# Generated by Django 3.2.11 on 2022-01-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Disply_picture', models.JSONField()),
                ('Admin_ID', models.CharField(max_length=100)),
                ('Contact_Number', models.IntegerField()),
                ('Email_adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_adress', models.CharField(max_length=100)),
                ('Passwords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Time', models.DateTimeField()),
                ('status', models.TextField(max_length=15)),
                ('Total_bill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Contact_Number', models.IntegerField()),
                ('Email_adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Test_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to=None)),
                ('Estimates_testing_time', models.TimeField()),
                ('Test_sample_attributes', models.JSONField()),
                ('Test_sample_respectivley', models.JSONField()),
                ('Price', models.IntegerField()),
                ('Test_times', models.IntegerField()),
                ('Department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('Result_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Result', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to=None)),
                ('Details', models.JSONField()),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Admin',
            fields=[
                ('Report_Admin_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Contact_Number', models.IntegerField()),
                ('Email_adress', models.CharField(max_length=100)),
                ('Department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Test_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test'),
        ),
        migrations.AddField(
            model_name='order',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
    ]
