# Generated by Django 4.0.2 on 2022-02-05 21:22

from django.db import migrations, models
import django.db.models.deletion
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Email_adress',
            new_name='Email_Address',
        ),
        migrations.RenameField(
            model_name='login_manager',
            old_name='Email_adress',
            new_name='Email_Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Total_bill',
            new_name='Total_Bill',
        ),
        migrations.RenameField(
            model_name='report_admin',
            old_name='Email_adress',
            new_name='Email_Address',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Estimates_testing_time',
            new_name='Estimates_Testing_Time',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Test_sample_attributes',
            new_name='Test_Sample_Attributes',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Test_sample_respectivley',
            new_name='Test_Sample_Respectivley',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Test_times',
            new_name='Test_Times',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Disply_picture',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Email_adress',
        ),
        migrations.AddField(
            model_name='department',
            name='Display_picture',
            field=models.ImageField(default=1, upload_to=test_app.models.Department.convert_Image_Name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Email_Address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_app.login_manager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='Admin_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Department_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report_admin',
            name='Report_Admin_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='Image',
            field=models.ImageField(upload_to=test_app.models.Result.convert_Image_Name),
        ),
        migrations.AlterField(
            model_name='result',
            name='Result_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='Test_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Test_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=test_app.models.Test_Images.convert_Image_Name)),
                ('Test_Images_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
            ],
        ),
    ]
